import { InferGetStaticPropsType } from "next"
import { type } from "os"
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Layout from "../components/Layout"


type Driver = {
    id: string
    firstName: string
    lastName : string
    email: string
    age : string
    gender: string
    
}

export const getStaticProps = async() => {
    const response = await fetch("http://localhost:3000/api/users")
    const drivers: Driver[] = await response.json()
   
    return{
        props:{ 
            drivers,
    
        },
    }
    
}

function UserList({drivers}: InferGetStaticPropsType<typeof getStaticProps>){
    return(
         <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>

      </div>
      
      <main className={styles.main}>
      <form action="/api/users" method="post">

<label htmlFor='firstName'>First Name: </label>
<input type="text" id="firstName" name="firstName" /> <br/><br/>

<label htmlFor='lastName'>Last name:</label>
<input type="text" id="lastName" name="lastName" /><br/><br/>

<label htmlFor='email'>Email:    </label>
<input type="text" id="email" name="email" /> <br/><br/>

<label htmlFor='age'>Age: </label>
<input type="text" id="age" name="age" /><br/><br/>

<label htmlFor='gender'>Gender: </label>
<input type="text" id="gender" name="gender" /> 
<div>
<button type="submit">Submit</button>
</div>

</form>
<h1>List of users</h1>
        {drivers.map((user) => {
            return (
                <div key={user.id}>
                    {user.id} , {user.firstName} , {user.lastName} , {user.email} , {user.age} , {user.gender}
                </div>
            )
        }
        )}
			</main>
      
    </div>
        
    )
}

export default UserList

