import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as React from 'react';
import Box from '@mui/material/Box';
import Stack from '@mui/material/Stack';
import Input from '@mui/material/Input';
import FormHelperText from '@mui/material/FormHelperText';
import InputLabel from '@mui/material/InputLabel';
import TextField from '@mui/material/TextField';
import FormControl from '@mui/material/FormControl';
import Button from '@mui/material/Button';
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ul>
      <li>
        <Link href="#">
          <a>Home</a>
        </Link>
      </li>
      <li>
        <Link href="/about">
          <a>About Us</a>
        </Link>
      </li>
      <li>
        <Link href="/blog">
          <a>Blog Post</a>
        </Link>
      </li>
    </ul>
 */}
    <form action="/api/form" method="post">

  <label htmlFor='first'>First name:</label>
  <input type="text" id="first" name="first" /> 

  <label htmlFor='last'>Last name:</label>
  <input type="text" id="last" name="last" />

  <label htmlFor='email'>Email:</label>
  <input type="text" id="email" name="first" /> 

  <label htmlFor='last'>Age:</label>
  <input type="text" id="age" name="last" />

  <label htmlFor='first'>Gender:</label>
  <input type="text" id="gender" name="first" /> 


  <button type="submit">Submit</button>
</form>




{/*       <main className={styles.main}>
        <h3 className={styles.h3}> Contact form <a href="https://nextjs.org">Abdre!</a>  </h3>

    <Stack spacing={2} direction="column">
      <TextField id="standard-basic" label="First name" variant="standard" />
      <TextField id="standard-basic" label="Last name" variant="standard" />
      <TextField id="standard-basic" label="Email" variant="standard" />
      <TextField id="standard-basic" label="Gender" variant="standard" />
      <Button variant="contained">Contained</Button>
      <Button variant="outlined">Outlined</Button>
    </Stack>

<div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h3>personal information</h3>
            <p>my name is abdurehman redi. I live in addis abeba</p>
          

          </a>
          
          
          
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

 {/*      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}





export default Home
